In [1]:
import numpy as np

In [15]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.flip(arr, axis=0)

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [19]:
arr2 = arr.copy()

In [20]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr2[2,2]=345

In [22]:
arr2

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8, 345]])

In [23]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr *10

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [25]:
arr % 2

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]], dtype=int32)

In [26]:
arr % 2 ==0

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [27]:
arr[arr%2==0]

array([2, 4, 6, 8])

In [ ]:
arr = 