In [87]:
import numpy as np

In [88]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [89]:
arr[2,2]

11

In [90]:
arr[0:2   ,2]

array([3, 7])

In [94]:
arr[0:2, 0:2]=10
arr

array([[10, 10,  3,  4],
       [10, 10,  7,  8],
       [ 9, 10, 11, 12]])

In [79]:
arr.reshape(4,3)

array([[10, 10,  3],
       [ 4, 10, 10],
       [ 7,  8,  9],
       [10, 11, 12]])

In [81]:
arr.resize(4,3)
arr


array([[10, 10,  3],
       [ 4, 10, 10],
       [ 7,  8,  9],
       [10, 11, 12]])

In [83]:
arr1 = arr.flatten()

In [84]:
arr1

array([10, 10,  3,  4, 10, 10,  7,  8,  9, 10, 11, 12])

In [85]:
arr

array([[10, 10,  3],
       [ 4, 10, 10],
       [ 7,  8,  9],
       [10, 11, 12]])

In [95]:
arr.transpose()


array([[10, 10,  9],
       [10, 10, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])